# Generated by Django 6.0.5 on 2026-07-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Введите страну",
                max_length=50,
                null=True,
                verbose_name="Страна",
            ),
        ),
    ]
