# Generated by Django 6.0.5 on 2026-06-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="BlogEntry",
        ),
    ]
