# Generated by Django 6.0.5 on 2026-07-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_contact_last_name_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("published", "Опубликовано"),
                    ("unpublished", "Неопубликовано"),
                ],
                default="unpublished",
                help_text="Укажите статус публикации",
                max_length=15,
                verbose_name="Статус публикации",
            ),
        ),
    ]
